name=LapMCP23017
version=1.0.3
author=LucyAmyPhotography
maintainer=Lucy Amanda Berry
sentence=A simple library to support the MCP23017 I2C I/O expander chip.
paragraph=LapMCP23017 is a simple library to support the MCP23017 I2C I/O expander chip. It enables bit by bit access to reading and writing, through digitalRead() and digitalWrite(), and 16-bit read and writes with read() and write(). Likewise it has pinMode() to set the mode of a pin, and portMode() to set the mode of all 16 I/O pins.
url="https://github.com/lucyamy/LapMCP23017"
architectures=*

