name=LapMCP23017
version=1.0.0
author=LucyAmyPhotography
maintainer=Lucy Amanda Berry
sentence=MCP23017 I2C Port expander library.
paragraph=A simple library to drive the MCP23017 I2C I/O expander chip.
url="https://github.com/lucyamy/LapMCP23017"
architectures=*

